// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJb1fB5U8JJ3tg7YKB2AQOsv6eBvh878Y',
    appId: '1:68148678191:web:6e0fed148f3e700b6e40da',
    messagingSenderId: '68148678191',
    projectId: 'ourwatch-4f73f',
    authDomain: 'ourwatch-4f73f.firebaseapp.com',
    storageBucket: 'ourwatch-4f73f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7eIxvbhp3t904sclDXeEVHuktRvldm3U',
    appId: '1:68148678191:android:c2753c924f52499e6e40da',
    messagingSenderId: '68148678191',
    projectId: 'ourwatch-4f73f',
    storageBucket: 'ourwatch-4f73f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDREEchTqgpl_H7tg7ySMxN7LzwThEJGxc',
    appId: '1:68148678191:ios:ec13cb9f0d831ce16e40da',
    messagingSenderId: '68148678191',
    projectId: 'ourwatch-4f73f',
    storageBucket: 'ourwatch-4f73f.firebasestorage.app',
    iosBundleId: 'com.example.ourwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDREEchTqgpl_H7tg7ySMxN7LzwThEJGxc',
    appId: '1:68148678191:ios:ec13cb9f0d831ce16e40da',
    messagingSenderId: '68148678191',
    projectId: 'ourwatch-4f73f',
    storageBucket: 'ourwatch-4f73f.firebasestorage.app',
    iosBundleId: 'com.example.ourwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJb1fB5U8JJ3tg7YKB2AQOsv6eBvh878Y',
    appId: '1:68148678191:web:253a567eab479ca16e40da',
    messagingSenderId: '68148678191',
    projectId: 'ourwatch-4f73f',
    authDomain: 'ourwatch-4f73f.firebaseapp.com',
    storageBucket: 'ourwatch-4f73f.firebasestorage.app',
  );
}
